name: Test and Lint
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r publisher/requirements.txt
        pip install -r subscriber/requirements.txt
        pip install -r simulated_service/requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd)/publisher:$(pwd)/subscriber:$(pwd)/simulated_service pytest
